# Available placeholders for file names and formats:
#   {date} - Current date as variable-formats.date
#   {time} - Current time as variable-formats.time
#   {player} - The player's name (*CONSOLE* for console commands)
#   {uuid} - Player's UUID (empty for console commands)
#   {ip} - Player's IP address (empty for console commands or if not available)
#   {full_command} - The command executed excluding the '/'
#   {base_command} - The command executed excluding the '/' and any arguments
#   {arguments} - The arguments provided to the command, empty if none


# Toggle all logging features (basically the entire plugin)
enabled: true

# These filters apply to ALL command loggers (combined, players, and console) and are considered first
# All filters use regex (see https://regex101.com)
# Filters can be applied to any logger! Exclude filters override include filters!
filters:
  # If a full command (excluding the /) matches this regex, it WILL be logged
  # Example: "op.*" would log all /op commands even if another filter excludes them
  include: ""
  # If a full command (excluding the /) matches this regex, it will NOT be logged
  # Example: "help.*" would exclude all /help commands from being logged
  exclude: ""

# Configurable formats for some variables, such as date and time
variable-formats:
  # https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
  date:
    file-names: "yyyy-MM-dd"
    formats: "MM-dd-yyyy"
  # https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
  time:
    file-names: "HH-mm-ss"
    formats: "HH:mm:ss"

# Combined player and console loggers (fields: enabled, file-name, filter, format)
# Several examples are provided below
loggers:
  # This is the "combined" logger for ALL commands
  - enabled: true
    file-name: "all.log"
    format: "[{date} {time}] [{player}] /{full_command}"
  # This logger creates a separate log file for each day
  - enabled: false
    file-name: "all/{date}.log"
    format: "[{time}] [{player}] /{full_command}"
  # This logger creates a log file only for /op commands
  - enabled: false
    file-name: "{base_command}.log"
    filters:
      include: "op.*"
    format: "[{date} {time}] [{player}] /{full_command}"

# Commands executed by players
players:
  # Toggle all player command loggers
  enabled: true

  # These filters apply to all player-ran command loggers
  # These are considered after the global filters but before individual logger filters
  filter:
    include: ""
    exclude: ""

  # Loggers for player commands (fields: enabled, file-name, required-permission, filters, format)
  # Several examples are provided below
  loggers:
    # This is the "combined" logger for ALL player commands
    - enabled: true
      file-name: "players.log"
      format: "[{date} {time}] [{player}] /{full_command}"
    # This logger creates a separate log file for each player based on their UUID
    - enabled: true
      file-name: "players/{uuid}.log"
      format: "[{date} {time}] /{full_command}"
    # This logger creates a separate log file for each player for each day, excluding /login commands
    - enabled: false
      file-name: "players/{uuid}/{date}.log"
      filters:
        exclude: "login.*"
      format: "[{time}] /{full_command}"
    # This logger creates a log file for all players with the group.mod permission
    - enabled: false
      file-name: "players/mods.log"
      required-permission: "group.mod"
      format: "[{date} {time}] [{player}] /{full_command}"

# Commands executed by the console
console:
  # Toggle all console command loggers
  enabled: true

  # These filters apply to all console command loggers
  # These are considered after the global filters but before individual logger filters
  filters:
    include: ""
    exclude: ""

  # Loggers for console commands (fields: enabled, file-name, filters, format)
  # Several examples are provided below
  loggers:
    # This is the "combined" logger for ALL console commands
    - enabled: true
      file-name: "console.log"
      format: "[{date} {time}] /{full_command}"
    # This logger creates a separate log file for each day
    - enabled: true
      file-name: "console/{date}.log"
      format: "[{time}] /{full_command}"
    # This logger creates a log file excluding /save-all commands
    - enabled: false
      file-name: "console-no-saveall.log"
      filters:
        exclude: "save-all.*"
      format: "[{date} {time}] /{full_command}"
